/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Facade.FacadeInter;
import Facade.MainFacade;
import utiles.MyFactory;

/**
 *
 * @author Jairo_Otaku
 */
public class Primera extends javax.swing.JFrame {

    FacadeInter facade = (MainFacade) MyFactory.getObject("FACADE");

    /**
     * Creates new form Primera
     */
    public Primera() {
        initComponents();
        //AQUI LA CARGA DE LAS TABLAS
        TablaAlumno.setModel(facade.todoAlumnos());
        TablaAsignatura.setModel(facade.todoAsignaturas());
        TablaProfesor.setModel(facade.todoProfes());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelAlumno = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaAlumno = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnAgregarAlumno = new javax.swing.JButton();
        btnActualizarAlumno = new javax.swing.JButton();
        btnBorrarAlumno = new javax.swing.JButton();
        PanelProfesor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProfesor = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnAgregarProfesor = new javax.swing.JButton();
        btnActualizarProfesor = new javax.swing.JButton();
        btnBorrarProfesor = new javax.swing.JButton();
        PanelAsignatura = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaAsignatura = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnAgregarAsignatura = new javax.swing.JButton();
        btnActualizarAsignatura = new javax.swing.JButton();
        btnBorrarAsignatura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaAlumno);

        jPanel5.setLayout(new java.awt.GridLayout(0, 3));

        btnAgregarAlumno.setText("Agregar");
        jPanel5.add(btnAgregarAlumno);

        btnActualizarAlumno.setText("Actualizar");
        jPanel5.add(btnActualizarAlumno);

        btnBorrarAlumno.setText("Borrar");
        jPanel5.add(btnBorrarAlumno);

        javax.swing.GroupLayout PanelAlumnoLayout = new javax.swing.GroupLayout(PanelAlumno);
        PanelAlumno.setLayout(PanelAlumnoLayout);
        PanelAlumnoLayout.setHorizontalGroup(
            PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelAlumnoLayout.setVerticalGroup(
            PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAlumnoLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Alumnos", PanelAlumno);

        TablaProfesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaProfesor);

        jPanel7.setLayout(new java.awt.GridLayout(0, 3));

        btnAgregarProfesor.setText("Agregar");
        jPanel7.add(btnAgregarProfesor);

        btnActualizarProfesor.setText("Actualizar");
        jPanel7.add(btnActualizarProfesor);

        btnBorrarProfesor.setText("Borrar");
        jPanel7.add(btnBorrarProfesor);

        javax.swing.GroupLayout PanelProfesorLayout = new javax.swing.GroupLayout(PanelProfesor);
        PanelProfesor.setLayout(PanelProfesorLayout);
        PanelProfesorLayout.setHorizontalGroup(
            PanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelProfesorLayout.setVerticalGroup(
            PanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProfesorLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Profesores", PanelProfesor);

        TablaAsignatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TablaAsignatura);

        jPanel6.setLayout(new java.awt.GridLayout(0, 3));

        btnAgregarAsignatura.setText("Agregar");
        jPanel6.add(btnAgregarAsignatura);

        btnActualizarAsignatura.setText("Actualizar");
        jPanel6.add(btnActualizarAsignatura);

        btnBorrarAsignatura.setText("Borrar");
        jPanel6.add(btnBorrarAsignatura);

        javax.swing.GroupLayout PanelAsignaturaLayout = new javax.swing.GroupLayout(PanelAsignatura);
        PanelAsignatura.setLayout(PanelAsignaturaLayout);
        PanelAsignaturaLayout.setHorizontalGroup(
            PanelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelAsignaturaLayout.setVerticalGroup(
            PanelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAsignaturaLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Asignaturas", PanelAsignatura);
        PanelAsignatura.getAccessibleContext().setAccessibleName("Asignaturas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Primera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Primera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Primera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Primera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Primera().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelAlumno;
    public javax.swing.JPanel PanelAsignatura;
    public javax.swing.JPanel PanelProfesor;
    public javax.swing.JTable TablaAlumno;
    public javax.swing.JTable TablaAsignatura;
    public javax.swing.JTable TablaProfesor;
    public javax.swing.JButton btnActualizarAlumno;
    public javax.swing.JButton btnActualizarAsignatura;
    public javax.swing.JButton btnActualizarProfesor;
    public javax.swing.JButton btnAgregarAlumno;
    public javax.swing.JButton btnAgregarAsignatura;
    public javax.swing.JButton btnAgregarProfesor;
    public javax.swing.JButton btnBorrarAlumno;
    public javax.swing.JButton btnBorrarAsignatura;
    public javax.swing.JButton btnBorrarProfesor;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
