package Pojos;
// Generated 17-nov-2016 10:58:35 by Hibernate Tools 4.3.1

/**
 * Alumno generated by hbm2java
 */
public class Alumno implements java.io.Serializable {

    private String dni;
    private String nombre;
    private String apellidos;
    private String domicilio;
    private int telefono;
    private int acceso;

    public Alumno() {
    }

    public Alumno(String dni, String nombre, String apellidos, String domicilio, int telefono, int acceso) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.domicilio = domicilio;
        this.telefono = telefono;
        this.acceso = acceso;
    }

    public String getDni() {
        return this.dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getDomicilio() {
        return this.domicilio;
    }

    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    public int getTelefono() {
        return this.telefono;
    }

    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }

    public int getAcceso() {
        return this.acceso;
    }

    public void setAcceso(int acceso) {
        this.acceso = acceso;
    }

    //---------------  METODOS FACADE ------------------//
    


}
