package Pojos;
// Generated 17-nov-2016 10:58:35 by Hibernate Tools 4.3.1

/**
 * AsigNotaId generated by hbm2java
 */
public class AsigNotaId implements java.io.Serializable {

    private String dniAlum;
    private int codAsig;

    public AsigNotaId() {
    }

    public AsigNotaId(String dniAlum, int codAsig) {
        this.dniAlum = dniAlum;
        this.codAsig = codAsig;
    }

    public String getDniAlum() {
        return this.dniAlum;
    }

    public void setDniAlum(String dniAlum) {
        this.dniAlum = dniAlum;
    }

    public int getCodAsig() {
        return this.codAsig;
    }

    public void setCodAsig(int codAsig) {
        this.codAsig = codAsig;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof AsigNotaId)) {
            return false;
        }
        AsigNotaId castOther = (AsigNotaId) other;

        return ((this.getDniAlum() == castOther.getDniAlum()) || (this.getDniAlum() != null && castOther.getDniAlum() != null && this.getDniAlum().equals(castOther.getDniAlum())))
                && (this.getCodAsig() == castOther.getCodAsig());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getDniAlum() == null ? 0 : this.getDniAlum().hashCode());
        result = 37 * result + this.getCodAsig();
        return result;
    }

}
