package Pojos;
// Generated 02-dic-2016 14:09:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private int codigo;
     private String titulo;
     private int creditos;
     private Set aulasAsigs = new HashSet(0);
     private Set asigNotas = new HashSet(0);

    public Asignatura() {
    }

	
    public Asignatura(int codigo, String titulo, int creditos) {
        this.codigo = codigo;
        this.titulo = titulo;
        this.creditos = creditos;
    }
    public Asignatura(int codigo, String titulo, int creditos, Set aulasAsigs, Set asigNotas) {
       this.codigo = codigo;
       this.titulo = titulo;
       this.creditos = creditos;
       this.aulasAsigs = aulasAsigs;
       this.asigNotas = asigNotas;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public int getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(int creditos) {
        this.creditos = creditos;
    }
    public Set getAulasAsigs() {
        return this.aulasAsigs;
    }
    
    public void setAulasAsigs(Set aulasAsigs) {
        this.aulasAsigs = aulasAsigs;
    }
    public Set getAsigNotas() {
        return this.asigNotas;
    }
    
    public void setAsigNotas(Set asigNotas) {
        this.asigNotas = asigNotas;
    }




}


