package Pojos;
// Generated 17-nov-2016 10:58:35 by Hibernate Tools 4.3.1



/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private int codigo;
     private String titulo;
     private int creditos;

    public Asignatura() {
    }

    public Asignatura(int codigo, String titulo, int creditos) {
       this.codigo = codigo;
       this.titulo = titulo;
       this.creditos = creditos;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public int getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(int creditos) {
        this.creditos = creditos;
    }




}


