package Pojos;
// Generated 02-dic-2016 14:09:33 by Hibernate Tools 4.3.1



/**
 * AsigNota generated by hbm2java
 */
public class AsigNota  implements java.io.Serializable {


     private AsigNotaId id;
     private Alumno alumno;
     private Asignatura asignatura;
     private int nota;

    public AsigNota() {
    }

    public AsigNota(AsigNotaId id, Alumno alumno, Asignatura asignatura, int nota) {
       this.id = id;
       this.alumno = alumno;
       this.asignatura = asignatura;
       this.nota = nota;
    }
   
    public AsigNotaId getId() {
        return this.id;
    }
    
    public void setId(AsigNotaId id) {
        this.id = id;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }
    public int getNota() {
        return this.nota;
    }
    
    public void setNota(int nota) {
        this.nota = nota;
    }




}


