package Pojos;
// Generated 02-dic-2016 14:09:33 by Hibernate Tools 4.3.1



/**
 * AulasAsig generated by hbm2java
 */
public class AulasAsig  implements java.io.Serializable {


     private AulasAsigId id;
     private Asignatura asignatura;
     private Aulas aulas;
     private Profesor profesor;

    public AulasAsig() {
    }

    public AulasAsig(AulasAsigId id, Asignatura asignatura, Aulas aulas, Profesor profesor) {
       this.id = id;
       this.asignatura = asignatura;
       this.aulas = aulas;
       this.profesor = profesor;
    }
   
    public AulasAsigId getId() {
        return this.id;
    }
    
    public void setId(AulasAsigId id) {
        this.id = id;
    }
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }
    public Aulas getAulas() {
        return this.aulas;
    }
    
    public void setAulas(Aulas aulas) {
        this.aulas = aulas;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }




}


