package Pojos;
// Generated 02-dic-2016 14:09:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aulas generated by hbm2java
 */
public class Aulas  implements java.io.Serializable {


     private int NAula;
     private String nombreEdificio;
     private Set aulasAsigs = new HashSet(0);

    public Aulas() {
    }

	
    public Aulas(int NAula, String nombreEdificio) {
        this.NAula = NAula;
        this.nombreEdificio = nombreEdificio;
    }
    public Aulas(int NAula, String nombreEdificio, Set aulasAsigs) {
       this.NAula = NAula;
       this.nombreEdificio = nombreEdificio;
       this.aulasAsigs = aulasAsigs;
    }
   
    public int getNAula() {
        return this.NAula;
    }
    
    public void setNAula(int NAula) {
        this.NAula = NAula;
    }
    public String getNombreEdificio() {
        return this.nombreEdificio;
    }
    
    public void setNombreEdificio(String nombreEdificio) {
        this.nombreEdificio = nombreEdificio;
    }
    public Set getAulasAsigs() {
        return this.aulasAsigs;
    }
    
    public void setAulasAsigs(Set aulasAsigs) {
        this.aulasAsigs = aulasAsigs;
    }




}


