package Pojos;
// Generated 17-nov-2016 10:58:35 by Hibernate Tools 4.3.1

/**
 * Aulas generated by hbm2java
 */
public class Aulas implements java.io.Serializable {

    private int NAula;
    private String nombreEdificio;

    public Aulas() {
    }

    public Aulas(int NAula, String nombreEdificio) {
        this.NAula = NAula;
        this.nombreEdificio = nombreEdificio;
    }

    public int getNAula() {
        return this.NAula;
    }

    public void setNAula(int NAula) {
        this.NAula = NAula;
    }

    public String getNombreEdificio() {
        return this.nombreEdificio;
    }

    public void setNombreEdificio(String nombreEdificio) {
        this.nombreEdificio = nombreEdificio;
    }

}
