package Pojos;
// Generated 17-nov-2016 10:58:35 by Hibernate Tools 4.3.1



/**
 * AulasAsig generated by hbm2java
 */
public class AulasAsig  implements java.io.Serializable {


     private AulasAsigId id;

    public AulasAsig() {
    }

    public AulasAsig(AulasAsigId id) {
       this.id = id;
    }
   
    public AulasAsigId getId() {
        return this.id;
    }
    
    public void setId(AulasAsigId id) {
        this.id = id;
    }




}


