package Pojos;
// Generated 17-nov-2016 10:58:35 by Hibernate Tools 4.3.1

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

    private String dni;
    private String nombre;
    private String apellidos;
    private String domicilio;
    private int telefono;
    private String asignatura1;
    private String asignatura2;
    private String asignatura3;
    private String asignatura4;
    private String asignatura5;
    private String asignatura6;

    public Profesor() {
    }

    public Profesor(String dni, String nombre, String apellidos, String domicilio, int telefono) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.domicilio = domicilio;
        this.telefono = telefono;
    }

    public Profesor(String dni, String nombre, String apellidos, String domicilio, int telefono, String asignatura1, String asignatura2, String asignatura3, String asignatura4, String asignatura5, String asignatura6) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.domicilio = domicilio;
        this.telefono = telefono;
        this.asignatura1 = asignatura1;
        this.asignatura2 = asignatura2;
        this.asignatura3 = asignatura3;
        this.asignatura4 = asignatura4;
        this.asignatura5 = asignatura5;
        this.asignatura6 = asignatura6;
    }

    public String getDni() {
        return this.dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getDomicilio() {
        return this.domicilio;
    }

    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    public int getTelefono() {
        return this.telefono;
    }

    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }

    public String getAsignatura1() {
        return this.asignatura1;
    }

    public void setAsignatura1(String asignatura1) {
        this.asignatura1 = asignatura1;
    }

    public String getAsignatura2() {
        return this.asignatura2;
    }

    public void setAsignatura2(String asignatura2) {
        this.asignatura2 = asignatura2;
    }

    public String getAsignatura3() {
        return this.asignatura3;
    }

    public void setAsignatura3(String asignatura3) {
        this.asignatura3 = asignatura3;
    }

    public String getAsignatura4() {
        return this.asignatura4;
    }

    public void setAsignatura4(String asignatura4) {
        this.asignatura4 = asignatura4;
    }

    public String getAsignatura5() {
        return this.asignatura5;
    }

    public void setAsignatura5(String asignatura5) {
        this.asignatura5 = asignatura5;
    }

    public String getAsignatura6() {
        return this.asignatura6;
    }

    public void setAsignatura6(String asignatura6) {
        this.asignatura6 = asignatura6;
    }

}
